### ISSUE TITLE
PCB 

### ISSUE THREAD

**Issue by shahbazaly** [InES-HPMM/FPD-LinkIII_Raspberry_HW#1]
Hello, I have tried to get a PCB of piCam2fpdlink made from a company. I got a response from them about the polarity of u1, u2 and u3 components. Ca you tell me the correct polarity of these components so that the company could get it made for me ? Please see the attachment. Thank you.

![Screenshot_2020-10-30 fixed-term shahbaz rizvi sojus-software de - Posteingang - AfterLogic WebMail Pro](https://user-images.githubusercontent.com/73706851/97720675-d5f02a80-1ac8-11eb-93f2-f25e8c3ff629.png)
![Screenshot_2020-10-30 fixed-term shahbaz rizvi sojus-software de - Posteingang - AfterLogic WebMail Pro(2)](https://user-images.githubusercontent.com/73706851/97720679-d688c100-1ac8-11eb-8fad-a0464d3886ce.png)

**Comment by dariis** [comment]
On page 5 of the pdf the correct polarities of U1 and U2 are marked:
https://github.com/InES-HPMM/FPD-LinkIII_Raspberry_HW/blob/master/piCam2fpdlink/piCam2fpdlink_PCB_0v5.PDF

The the polarity of U3 is missing, thanks for pointing that out:
![grafik](https://user-images.githubusercontent.com/40891553/97742137-2923a680-1ae4-11eb-9c4d-bb0e7a0d196b.png)

**Comment by shahbazaly** [comment]
Thank you very much
