### ISSUE TITLE
Way to buy these boards?

### ISSUE THREAD

**Issue by lucasriepe** [InES-HPMM/FPD-LinkIII_Raspberry_HW#10]
Where did you produce these boards?
or is there any way to buy these boards?

**Comment by MichaelWaespe1** [comment]
Hi @lucasriepe  

You can order these PCBs from any reputable manufacturer with the Gerber files. However, we do not sell the PCBs.

Best regards, 
Michael

**Comment by lucasriepe** [comment]
> Hi @lucasriepe  
> 
> 
> 
> You can order these PCBs from any reputable manufacturer with the Gerber files. However, we do not sell the PCBs.
> 
> 
> 
> Best regards, 
> 
> Michael

first of all, thank you very much for answering! Where did you have yours built? because I can use the gerber but not the BOM or the pick and place

**Comment by MichaelWaespe1** [comment]
Hi @lucasriepe 

In which file types do you need the BOM and Pick and Place? I can recreate them for you in your preferred format. 

Best regards,
Michael
