### ISSUE TITLE
libcamera

### ISSUE THREAD

**Issue by shahbazaly** [InES-HPMM/FPD-LinkIII_Raspberry_HW#4]
Hello,
I am trying to get an image from libcamera but this error appears when I build qcam. Do you have any clue about the issue?
also how can I enable the module on menuconfig? maybe I have not done it right. Thanks in advance.
[20210113_121444.pdf](https://github.com/InES-HPMM/FPD-LinkIII_Raspberry_HW/files/5808838/20210113_121444.pdf)

**Comment by JanaUnderground** [comment]
Hi,

Unfortunately, we have not encountered that error yet. Was the loading of the ds90ub954 and imx219 modules successful? 
Could you send us a screenshot of the dmesg? 
`dmesg | grep ds90`
`dmesg | grep imx219`
Just so we can rule out an error with the modules.


We use menuconfig when we compile the kernel and kernel modules ourselves. You can crosscompile the kernel module for your raspberry pi (https://github.com/raspberrypi/linux). The readme should give the instructions on how to add our driver into the kernel.

For the menuconfig, I am attaching some screenshots from my menuconfig.
`make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- menuconfig`
In the menuconfig i pressed `/` to search. I searched for `ds90` and found the entry for fpd link module:
![Selection_140](https://user-images.githubusercontent.com/51925599/104479144-610a9800-55c3-11eb-956b-21aef18aa001.png)

Pressing (1) opens the first found entry and there i pressed space to change the icon `< >` to `<M>`.
![Selection_141](https://user-images.githubusercontent.com/51925599/104479423-b5157c80-55c3-11eb-8f7e-bd9af7818e8b.png)

After saving this menuconfig, the module will be included when you build the kernel.

**Comment by shahbazaly** [comment]
Thank you very much it works now :)
