### ISSUE TITLE
Special driver needed and virtual channel

### ISSUE THREAD

**Issue by loopy83** [InES-HPMM/FPD-LinkIII_Raspberry_HW#5]
Hi,

first of all - VERY interesting project! Thank you very much!

I have two questions:
> 1. I have a "special TOF camera module " which requires a specific camera driver to run on the RPI. Can I just reuse this driver, or is any special driver for the ds90ub95x needed? I saw your driver here: https://github.com/InES-HPMM/FPD-LinkIII_ds90ub95x
> So will the ds90ub95x behave like its own camera, or will it behave like the original camera?

> 2. Does this setup support Virtual Channel in MIPI?

Thank you very much!

**Comment by JanaUnderground** [comment]
Hi, 
Sorry for the late answer. Very happy to hear you like the project.

1. The ds90ub95x driver makes a transparent link. This means after the driver has run, the camera behaves like the original camera. In our example with the imx219 sensor, after the ds90ub95x driver has run, the imx219 driver can be run unchanged. The most important point is that while booting the ds90 driver needs to be run before the camera driver.

2. The ds90ub954 deserializer supports virtual channel. So should our driver, however this could not be tested. Not sure if the Raspberry Pi can handle virtual channels.
