### ISSUE TITLE
Can this be used to output DSI to FPD-LinkIII for automotive displays?

### ISSUE THREAD

**Issue by patfelst** [InES-HPMM/FPD-LinkIII_Raspberry_HW#6]
Hi there, could this be adapted essentially in reverse so the RPi can output video on DSI connector, to FPD-LinkIII format to display RPi on an automotive display, e.g. BMW which uses a FAKRA 4-pin interface?

Thanks.

**Comment by JanaUnderground** [comment]
Hi,
Unfortunately, I don't think this will work even though both protocols are quite similar. TI does offer seperate chips for DSI applications: https://www.ti.com/interface/fpd-link-serdes/display-serdes/overview.html

**Comment by patfelst** [comment]
Thanks I'll look into those TI chips.
