### ISSUE TITLE
Guidance on Libcamera-qcam step

### ISSUE THREAD

**Issue by Etherity** [InES-HPMM/FPD-LinkIII_Raspberry_HW#7]
Hello,

Thank you for sharing this project on github. I've tried following your steps to get my board up and running and there are some issues with the IMX219 sensor not registering. I've attached a picture at the step I'm having trouble with along with the error message for the IMX219. Is there any assistance you could provide me?

I've tried both buster and bullseye but had the same issues pop up. 

![2023-07-12-135120_1920x1080_scrot](https://github.com/InES-HPMM/FPD-LinkIII_Raspberry_HW/assets/32962432/5cbb010b-c4c3-4d9b-b680-a8f0c0b25adb)

**Comment by JanaUnderground** [comment]
Hi,

Are you using Raspberry Pi 3 or 4?
We'll try to reproduce it.

**Comment by MichaelWaespe1** [comment]
Hi @Etherity 

We have made a new release for kernel version 6.1 on the driver repository https://github.com/InES-HPMM/FPD-LinkIII_ds90ub95x. Please try again and don't hesitate to raise the issue again if the problems persist.

**Comment by MichaelWaespe1** [comment]
Hi @Etherity

We have made a new release for kernel version 6.1 on the driver repository https://github.com/InES-HPMM/FPD-LinkIII_ds90ub95x. Please try again and don't hesitate to raise the issue again if the problems persist.
