### ISSUE TITLE
can you help me change the SMA port to fakra?

### ISSUE THREAD

**Issue by fancong5201314** [InES-HPMM/FPD-LinkIII_Raspberry_HW#8]
I am a hardware novice, and there is no PCB diagram in the hardware information provided. Can you help me change the SMA port to fakra port?
Thanks a lot.

**Comment by MichaelWaespe1** [comment]
Hello @fancong5201314 
If you are interested in the schematic and PCB files, please contact me directly at:
waep"at"zhaw.ch

**Comment by MichaelWaespe1** [comment]
Hello @fancong5201314 
If you are interested in the schematic and PCB files, please contact me directly at:
waep"at"zhaw.ch
