### ISSUE TITLE
Raspberry Pi Camera v3 support

### ISSUE THREAD

**Issue by jess-sys** [InES-HPMM/FPD-LinkIII_Raspberry_HW#9]
Hi,

Thank you for this amazing work. 

By any chance, is this project compatible with the newer RPi Camera v3 model ?

Thanks,

—
Jessy

**Comment by MichaelWaespe1** [comment]
Hi @jess-sys 

The hardware also supports the Raspi camera module v3. Please also have a look at our driver repository, where we have recently made a release that supports the Raspi Cam V3.

Best regards
Michael
